// import 'package:flutter/material.dart';
// import 'package:flutter/services.dart';
// import 'dart:math';
// import 'package:flutter_tts/flutter_tts.dart';

// class TambolaPage extends StatefulWidget {
//   const TambolaPage({super.key});

//   @override
//   State<TambolaPage> createState() => _TambolaPageState();
// }

// class _TambolaPageState extends State<TambolaPage> with WidgetsBindingObserver {
//   int generatedNumber = 0;
//   List<int> highlightedNumbers = [];
//   FlutterTts flutterTts = FlutterTts();
//   bool isGenerateButtonActive = true;
//   bool isAutoGenerateEnabled = false;
//   bool isPlaying = false;
//   bool areButtonsDisabled = false;
//   double autoGenerateDelay = 3.0;
//   bool isVolumeOn = true;

//   @override
//   void initState() {
//     super.initState();
//     WidgetsBinding.instance.addObserver(this);
//     configureTts();
//   }

//   @override
//   void dispose() {
//     WidgetsBinding.instance.removeObserver(this);
//     flutterTts.stop();
//     super.dispose();
//   }

//   @override
//   void didChangeAppLifecycleState(AppLifecycleState state) {
//     if (state == AppLifecycleState.paused ||
//         state == AppLifecycleState.inactive) {
//       stopAutoGeneration();
//       flutterTts.stop();
//     } else if (state == AppLifecycleState.resumed) {
//       if (isAutoGenerateEnabled) {
//         startAutoGeneration();
//       }
//     }
//   }

// //audio style
//   void configureTts() async {
//     await flutterTts.setLanguage("en-US");
//     await flutterTts.setPitch(1.0);
//     await flutterTts.setSpeechRate(0.5);
//     await flutterTts.awaitSpeakCompletion(true);
//   }

//   void announceNumber(int number) {
//     if (isVolumeOn) {
//       flutterTts.speak(number.toString());
//     }
//   }

//   void generateRandomNumber() async {
//     if (!isGenerateButtonActive || (!isAutoGenerateEnabled && isPlaying))
//       return;

//     setState(() {
//       isGenerateButtonActive = false;
//     });

//     Random random = Random();
//     int newNumber;

//     do {
//       newNumber = random.nextInt(90) + 1;
//     } while (highlightedNumbers.contains(newNumber));

//     setState(() {
//       generatedNumber = newNumber;
//       highlightedNumbers.add(newNumber);
//     });

//     announceNumber(generatedNumber);
//     print('Generated Number: $generatedNumber');

//     if (highlightedNumbers.length == 90) {
//       Future.delayed(const Duration(milliseconds: 1500), () {
//         _showAllNumbersCalledDialog();
//       });
//     } else {
//       Future.delayed(
//           Duration(
//               seconds: isAutoGenerateEnabled ? autoGenerateDelay.round() : 2),
//           () {
//         setState(() {
//           isGenerateButtonActive = true;
//         });

//         if (isAutoGenerateEnabled && isPlaying) {
//           generateRandomNumber();
//         }
//       });
//     }
//   }

//   void toggleVolume() {
//     setState(() {
//       isVolumeOn = !isVolumeOn;
//       if (!isVolumeOn) {
//         flutterTts.stop();
//       }
//     });
//   }

//   void _showAllNumbersCalledDialog() {
//     showDialog(
//       barrierDismissible: false,
//       context: context,
//       builder: (BuildContext context) {
//         return AlertDialog(
//           title: const Text('All Numbers Called!'),
//           content: const Text(
//               'Congratulations! All numbers have been called. What would you like to do?'),
//           actions: [
//             TextButton(
//               onPressed: () {
//                 resetGame();
//                 Navigator.of(context).pop();
//               },
//               child: const Text('Reset Game'),
//             ),
//             //button disable afer close
//             TextButton(
//               onPressed: () {
//                 setState(() {
//                   areButtonsDisabled = true;
//                 });
//                 Navigator.of(context).pop();
//               },
//               child: const Text('Close'),
//             ),
//           ],
//         );
//       },
//     );
//   }

//   void _showNumbersCalledListDialog() {
//     showDialog(
//       barrierDismissible: false,
//       context: context,
//       builder: (BuildContext context) {
//         List<Widget> numberWidgets = highlightedNumbers.isEmpty
//             ? [const Text('No number called...')]
//             : highlightedNumbers.map((number) {
//                 return Container(
//                   height: 33,
//                   width: 33,
//                   margin: const EdgeInsets.all(4.0),
//                   decoration: BoxDecoration(
//                       shape: BoxShape.circle,
//                       color: Colors.transparent,
//                       border: Border.all(color: Colors.black)),
//                   child: Center(
//                     child: Text(
//                       number.toString(),
//                       style: const TextStyle(
//                         fontSize: 16,
//                         color: Colors.black,
//                       ),
//                     ),
//                   ),
//                 );
//               }).toList();

//         return AlertDialog(
//           title: Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               const Text(
//                 'History',
//                 style: TextStyle(fontSize: 22),
//               ),
//               GestureDetector(
//                 onTap: () async {
//                   Navigator.pop(context);
//                 },
//                 child: Container(
//                   height: 30,
//                   width: 30,
//                   decoration: BoxDecoration(
//                     color: Colors.transparent,
//                     borderRadius: BorderRadius.circular(30),
//                     //  border: Border.all(color: Colors.black),
//                   ),
//                   child: const Center(
//                     child: Icon(
//                       Icons.close,
//                       color: Colors.black,
//                       size: 25,
//                     ),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//           content: SizedBox(
//             width: double.maxFinite, // Make the content width flexible
//             child: Wrap(
//               alignment: WrapAlignment.center, // Center the circles
//               children: numberWidgets,
//             ),
//           ),
//           // actions: [
//           //   TextButton(
//           //     onPressed: () {
//           //       resetGame();
//           //       Navigator.of(context).pop();
//           //     },
//           //     child: const Text('Reset Game'),
//           //   ),
//           //   TextButton(
//           //     onPressed: () {
//           //       Navigator.of(context).pop();
//           //     },
//           //     child: const Text('Close'),
//           //   ),
//           // ],
//         );
//       },
//     );
//   }

//   void resetGame() {
//     setState(() {
//       generatedNumber = 0;
//       highlightedNumbers.clear();
//       isPlaying = false;
//       isAutoGenerateEnabled = false;
//       isGenerateButtonActive = true;
//       areButtonsDisabled = false;
//     });
//   }

//   void startAutoGeneration() {
//     setState(() {
//       isPlaying = true;
//     });
//     generateRandomNumber();
//   }

//   void stopAutoGeneration() {
//     setState(() {
//       isPlaying = false;
//     });
//   }

//   void toggleAutoGeneration() {
//     if (isPlaying) {
//       stopAutoGeneration();
//     } else {
//       startAutoGeneration();
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     SystemChrome.setSystemUIOverlayStyle(
//       const SystemUiOverlayStyle(
//         statusBarColor: Colors.black,
//         statusBarIconBrightness: Brightness.light,
//         systemNavigationBarColor: Colors.black,
//         systemNavigationBarIconBrightness: Brightness.light,
//       ),
//     );
//     return Scaffold(
//       body: Column(
//         // mainAxisAlignment: MainAxisAlignment.start,
//         children: [
//           //SizedBox(height: 40),
//           Padding(
//             padding: const EdgeInsets.only(
//               left: 10,
//               right: 10,
//               top: 50,
//             ),
//             child: Row(
//               mainAxisAlignment: MainAxisAlignment.spaceBetween,
//               children: [
//                 GestureDetector(
//                   onTap: () async {
//                     Navigator.pop(context);
//                   },
//                   child: Card(
//                     elevation: 10,
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(40),
//                     ),
//                     child: Container(
//                       height: 40,
//                       width: 40,
//                       padding: const EdgeInsets.only(left: 8),
//                       decoration: BoxDecoration(
//                         color: Colors.white,
//                         borderRadius: BorderRadius.circular(10),
//                       ),
//                       child: const Center(
//                         child: Icon(
//                           Icons.arrow_back_ios,
//                           color: Colors.black,
//                           size: 25,
//                         ),
//                       ),
//                     ),
//                   ),
//                 ),
//                 // SizedBox(height: 100),
//                 // Padding(
//                 //   padding: const EdgeInsets.only(top: 50),
//                 // child: Container(
//                 //   width: 100,
//                 //   height: 100,
//                 //   alignment: Alignment.center,
//                 //   decoration: BoxDecoration(
//                 //     // border:
//                 //     //     Border.all(color: const Color(0xFFA388EE), width: 2),
//                 //     // gradient: const LinearGradient(
//                 //     //   colors: [
//                 //     //     Color(0xFF69D2E7),
//                 //     //     Color(0xFFB39DDB),
//                 //     //     Color(0xFFFFB2EF),
//                 //     //   ],
//                 //     //   begin: Alignment.topLeft,
//                 //     //   end: Alignment.bottomRight,
//                 //     // ),
//                 //     borderRadius: BorderRadius.circular(20),
//                 //   ),
//                 //   child: Container(
//                 //     height: 80,
//                 //     width: 80,
//                 //     decoration: BoxDecoration(
//                 //       color: const Color.fromARGB(255, 248, 241, 174),
//                 //       borderRadius: BorderRadius.circular(20),
//                 //       border: Border.all(
//                 //           color: const Color(0xFFA388EE), width: 2),
//                 //     ),
//                 //     child: Center(
//                 //       child: Text(
//                 //         '$generatedNumber',
//                 //         style: const TextStyle(
//                 //           fontSize: 40,
//                 //           color: Colors.black,
//                 //         ),
//                 //       ),
//                 //     ),
//                 //   ),
//                 // ),
//                 // ),
//                 // const SizedBox(width: 90),

//                 Card(
//                   elevation: 10,
//                   shape: RoundedRectangleBorder(
//                     borderRadius: BorderRadius.circular(40),
//                   ),
//                   child: Container(
//                     height: 40,
//                     width: 40,
//                     decoration: BoxDecoration(
//                       color: Colors.white,
//                       borderRadius: BorderRadius.circular(10),
//                     ),
//                     child: Center(
//                       child: IconButton(
//                         onPressed: toggleVolume,
//                         icon: Icon(
//                           isVolumeOn
//                               ? Icons.volume_up
//                               : Icons.volume_off, // Toggle icon
//                         ),
//                         color: Colors.black,
//                         iconSize: 25,
//                       ),
//                     ),
//                   ),
//                 ),
//               ],
//             ),
//           ),
//           const SizedBox(height: 50),
//           Expanded(
//             child: GridView.builder(
//               padding: const EdgeInsets.only(left: 20, right: 20),
//               gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
//                 crossAxisCount: 10,
//                 childAspectRatio: 0.8,
//               ),
//               itemCount: 90,
//               itemBuilder: (context, index) {
//                 int currentNumber = index + 1;
//                 Color boxColor;
//                 if (currentNumber == generatedNumber) {
//                   boxColor = const Color(0xFFFFB2EF);
//                 } else if (highlightedNumbers.contains(currentNumber)) {
//                   boxColor = const Color(0xFFA388EE);
//                 } else {
//                   boxColor = const Color.fromARGB(255, 248, 241, 174);
//                 }

//                 return Container(
//                   decoration: BoxDecoration(
//                       color: Colors.transparent,
//                       border: Border.all(color: Colors.grey, width: 0.5)),
//                   child: Padding(
//                     padding: const EdgeInsets.all(2.0),
//                     child: Container(
//                       decoration: BoxDecoration(
//                         color: boxColor,
//                         shape: BoxShape.circle,
//                         // borderRadius: BorderRadius.circular(60),
//                       ),
//                       child: Center(
//                         child: Text(
//                           '$currentNumber',
//                           style: const TextStyle(fontSize: 14),
//                         ),
//                       ),
//                     ),
//                   ),
//                 );
//               },
//             ),
//           ),
//           Padding(
//             padding: EdgeInsets.only(
//               left: MediaQuery.of(context).devicePixelRatio > 3 ? 10 : 30,
//               right: MediaQuery.of(context).devicePixelRatio > 3 ? 10 : 30,
//               bottom: 20,
//             ),
//             child: Row(
//               mainAxisAlignment: MainAxisAlignment.center,
//               children: [
//                 Expanded(
//                   flex: 2,
//                   child: Text(
//                     'Delay:${autoGenerateDelay.round()}s',
//                     style: TextStyle(fontSize: 18, color: Colors.black),
//                   ),
//                 ),
//                 Expanded(
//                   flex: 6,
//                   child: Slider(
//                     value: autoGenerateDelay,
//                     min: 3,
//                     max: 10,
//                     divisions: 7,
//                     label: '${autoGenerateDelay.round()}s',
//                     onChanged: (value) {
//                       setState(() {
//                         autoGenerateDelay = value;
//                       });
//                     },
//                   ),
//                 ),
//                 // Expanded(
//                 //   child: Text(
//                 //     '${autoGenerateDelay.round()}s',
//                 //     style: const TextStyle(fontSize: 16, color: Colors.black),
//                 //   ),
//                 // ),
//               ],
//             ),
//           ),
//           // Padding(
//           //   padding: const EdgeInsets.symmetric(vertical: 20.0),
//           //   child: Row(
//           //       mainAxisAlignment: MainAxisAlignment.spaceAround,
//           //       children: [
//           //         buildCustomButton(
//           //           '  History  ',
//           //           () {
//           //             if (isPlaying) {
//           //               stopAutoGeneration();
//           //             }
//           //             _showNumbersCalledListDialog();
//           //           },
//           //         ),
//           //         const SizedBox(width: 10),
//           //         buildCustomButton('  Restart  ', resetGame)
//           //       ]),
//           // ),
//           // const SizedBox(height: 40),

//           Padding(
//             padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 5.0),
//             child: Column(
//               children: [
//                 Row(
//                   mainAxisAlignment: MainAxisAlignment.spaceBetween,
//                   children: [
//                     Column(
//                       children: [
//                         Column(children: [
//                           const Text(
//                             'Auto',
//                             style: TextStyle(color: Colors.black, fontSize: 16),
//                           ),
//                           const SizedBox(width: 4),
//                           Transform.scale(
//                             scale: 1.3,
//                             child: Switch(
//                               value: isAutoGenerateEnabled,
//                               onChanged: (value) {
//                                 setState(() {
//                                   isAutoGenerateEnabled = value;
//                                   if (!value) {
//                                     stopAutoGeneration();
//                                   }
//                                 });
//                               },
//                               activeColor: const Color(0xFFA388EE),
//                               inactiveThumbColor: Colors.white,
//                             ),
//                           ),
//                         ]),
//                         const SizedBox(height: 7),
//                         Column(
//                           children: [
//                             const Text(
//                               'Restart',
//                               style:
//                                   TextStyle(color: Colors.black, fontSize: 16),
//                             ),
//                             const SizedBox(height: 2),
//                             Container(
//                               height: 40,
//                               width: 45,
//                               decoration: BoxDecoration(
//                                 borderRadius: BorderRadius.circular(10),
//                                 color: Colors.transparent,
//                                 border:
//                                     Border.all(color: Colors.black, width: 2),
//                               ),
//                               child: Center(
//                                 child: GestureDetector(
//                                   onTap: resetGame,
//                                   child: const Icon(
//                                     Icons.refresh,
//                                     color: Colors.black,
//                                     size: 30,
//                                   ),
//                                 ),
//                               ),
//                             ),
//                           ],
//                         )
//                       ],
//                     ),
//                     Container(
//                       width: 100,
//                       height: 100,
//                       alignment: Alignment.center,
//                       decoration: BoxDecoration(
//                         // border:
//                         //     Border.all(color: const Color(0xFFA388EE), width: 2),
//                         // gradient: const LinearGradient(
//                         //   colors: [
//                         //     Color(0xFF69D2E7),
//                         //     Color(0xFFB39DDB),
//                         //     Color(0xFFFFB2EF),
//                         //   ],
//                         //   begin: Alignment.topLeft,
//                         //   end: Alignment.bottomRight,
//                         // ),
//                         borderRadius: BorderRadius.circular(20),
//                       ),
//                       child: Container(
//                         height: 80,
//                         width: 80,
//                         decoration: BoxDecoration(
//                           color: const Color.fromARGB(255, 248, 241, 174),
//                           borderRadius: BorderRadius.circular(20),
//                           border: Border.all(
//                               color: const Color(0xFFA388EE), width: 2),
//                         ),
//                         child: Center(
//                           child: Text(
//                             '$generatedNumber',
//                             style: const TextStyle(
//                               fontSize: 40,
//                               color: Colors.black,
//                             ),
//                           ),
//                         ),
//                       ),
//                     ),
//                     Column(
//                       mainAxisAlignment: MainAxisAlignment.spaceAround,
//                       children: [
//                         Column(
//                           children: [
//                             if (!isAutoGenerateEnabled) ...[
//                               const Text(
//                                 'Generate ',
//                                 style: TextStyle(
//                                     color: Colors.black, fontSize: 16),
//                               ),
//                             ] else ...[
//                               Text(
//                                 isPlaying ? '   Pause   ' : '    Play     ',
//                                 style: const TextStyle(
//                                     color: Colors.black, fontSize: 16),
//                               ),
//                             ],
//                             const SizedBox(height: 2),
//                             if (!isAutoGenerateEnabled) ...[
//                               Container(
//                                 height: 43,
//                                 width: 45,
//                                 decoration: BoxDecoration(
//                                   borderRadius: BorderRadius.circular(10),
//                                   color: Colors.transparent,
//                                   border:
//                                       Border.all(color: Colors.black, width: 2),
//                                 ),
//                                 child: Center(
//                                   child: GestureDetector(
//                                     onTap: (isGenerateButtonActive &&
//                                             !areButtonsDisabled)
//                                         ? generateRandomNumber
//                                         : null,
//                                     child: const Icon(
//                                       Icons.play_arrow,
//                                       color: Colors.black,
//                                       size: 35,
//                                     ),
//                                   ),
//                                   //  IconButton(
//                                   //   onPressed: (isGenerateButtonActive &&
//                                   //           !areButtonsDisabled)
//                                   //       ? generateRandomNumber
//                                   //       : null,
//                                   //   icon: const Icon(Icons.play_arrow),
//                                   //   color: Colors.black,
//                                   //   iconSize: 25,
//                                   // ),
//                                 ),
//                               ),
//                             ] else ...[
//                               Container(
//                                 height: 43,
//                                 width: 45,
//                                 decoration: BoxDecoration(
//                                   borderRadius: BorderRadius.circular(10),
//                                   color: Colors.transparent,
//                                   border:
//                                       Border.all(color: Colors.black, width: 2),
//                                 ),
//                                 child: Center(
//                                   child: GestureDetector(
//                                     onTap: areButtonsDisabled
//                                         ? null
//                                         : toggleAutoGeneration,
//                                     child: Icon(
//                                       isPlaying
//                                           ? Icons.pause
//                                           : Icons.play_arrow,
//                                       color: Colors.black,
//                                       size: 35,
//                                     ),
//                                   ),
//                                   // IconButton(
//                                   //   onPressed: areButtonsDisabled
//                                   //       ? null
//                                   //       : toggleAutoGeneration,
//                                   //   icon: Icon(isPlaying
//                                   //       ? Icons.pause
//                                   //       : Icons.play_arrow),
//                                   //   color: Colors.black,
//                                   //   iconSize: 25,
//                                   // ),
//                                 ),
//                               ),
//                             ],
//                           ],
//                         ),
//                         const SizedBox(height: 7),
//                         Column(
//                           children: [
//                             const Text(
//                               'History',
//                               style:
//                                   TextStyle(color: Colors.black, fontSize: 16),
//                             ),
//                             const SizedBox(height: 2),
//                             Container(
//                               height: 40,
//                               width: 45,
//                               decoration: BoxDecoration(
//                                 borderRadius: BorderRadius.circular(10),
//                                 color: Colors.transparent,
//                                 border:
//                                     Border.all(color: Colors.black, width: 2),
//                               ),
//                               child: Center(
//                                 child: GestureDetector(
//                                   onTap: () {
//                                     if (isPlaying) {
//                                       stopAutoGeneration();
//                                     }
//                                     _showNumbersCalledListDialog();
//                                   },
//                                   child: const Icon(
//                                     Icons.book,
//                                     color: Colors.black,
//                                     size: 30,
//                                   ),
//                                 ),
//                                 //  IconButton(
//                                 //   onPressed: () {
//                                 //     if (isPlaying) {
//                                 //       stopAutoGeneration();
//                                 //     }
//                                 //     _showNumbersCalledListDialog();
//                                 //   },
//                                 //   icon: const Icon(Icons.book),
//                                 //   color: Colors.black,
//                                 //   iconSize: 25,
//                                 // ),
//                               ),
//                             ),
//                           ],
//                         ),
//                       ],
//                     )
//                     // if (!isAutoGenerateEnabled) ...[
//                     //   buildCustomButton(
//                     //     'Generate ',
//                     //     (isGenerateButtonActive && !areButtonsDisabled)
//                     //         ? generateRandomNumber
//                     //         : null,
//                     //   ),
//                     // ] else ...[
//                     //   buildCustomButton(
//                     //     isPlaying ? '   Pause   ' : '    Play     ',
//                     //     areButtonsDisabled ? null : toggleAutoGeneration,
//                     //   ),
//                     // ],
//                     // Column(children: [
//                     //   const Text(
//                     //     'Auto',
//                     //     style: TextStyle(color: Colors.black, fontSize: 16),
//                     //   ),
//                     //   const SizedBox(width: 7),
//                     //   Transform.scale(
//                     //     scale: 1.3,
//                     //     child: Switch(
//                     //       value: isAutoGenerateEnabled,
//                     //       onChanged: (value) {
//                     //         setState(() {
//                     //           isAutoGenerateEnabled = value;
//                     //           if (!value) {
//                     //             stopAutoGeneration();
//                     //           }
//                     //         });
//                     //       },
//                     //       activeColor: const Color(0xFFA388EE),
//                     //       inactiveThumbColor: Colors.white,
//                     //     ),
//                     //   ),
//                     // ]),
//                     // buildCustomButton('  Restart  ', resetGame)
//                   ],
//                 ),
//                 //  const SizedBox(height: 10),
//               ],
//             ),
//           ),

//           // Padding(
//           //   padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 5.0),
//           //   child: Column(
//           //     children: [
//           //       Row(
//           //         mainAxisAlignment: MainAxisAlignment.spaceBetween,
//           //         children: [
//           //           if (!isAutoGenerateEnabled) ...[
//           //             buildCustomButton(
//           //               'Generate ',
//           //               (isGenerateButtonActive && !areButtonsDisabled)
//           //                   ? generateRandomNumber
//           //                   : null,
//           //             ),
//           //           ] else ...[
//           //             buildCustomButton(
//           //               isPlaying ? '   Pause   ' : '    Play     ',
//           //               areButtonsDisabled ? null : toggleAutoGeneration,
//           //             ),
//           //           ],
//           //           Column(children: [
//           //             const Text(
//           //               'Auto',
//           //               style: TextStyle(color: Colors.black, fontSize: 16),
//           //             ),
//           //             const SizedBox(width: 7),
//           //             Transform.scale(
//           //               scale: 1.3,
//           //               child: Switch(
//           //                 value: isAutoGenerateEnabled,
//           //                 onChanged: (value) {
//           //                   setState(() {
//           //                     isAutoGenerateEnabled = value;
//           //                     if (!value) {
//           //                       stopAutoGeneration();
//           //                     }
//           //                   });
//           //                 },
//           //                 activeColor: const Color(0xFFA388EE),
//           //                 inactiveThumbColor: Colors.white,
//           //               ),
//           //             ),
//           //           ]),
//           //           buildCustomButton('  Restart  ', resetGame)
//           //         ],
//           //       ),
//           //       //  const SizedBox(height: 10),
//           //     ],
//           //   ),
//           // ),

//           // Row(
//           //   mainAxisAlignment: MainAxisAlignment.center,
//           //   children: [
//           //     GestureDetector(
//           //       onTap: () async {
//           //         _showNumbersCalledListDialog();
//           //       },
//           //       child: Container(
//           //         decoration: BoxDecoration(
//           //           color: Colors.transparent,
//           //           borderRadius: BorderRadius.circular(10),
//           //         ),
//           //         child: const Center(
//           //           child: Text('History',
//           //               style: TextStyle(
//           //                   fontSize: 18,
//           //                   fontWeight: FontWeight.w500,
//           //                   decoration: TextDecoration.underline,
//           //                   decorationThickness: 2)),
//           //         ),
//           //       ),
//           //     ),
//           //   ],
//           // ),
//           const SizedBox(height: 20),
//         ],
//       ),
//     );
//   }

//   Widget buildCustomButton(String text, VoidCallback? onPressed) {
//     return GestureDetector(
//       onTap: onPressed != null ? onPressed : () {},
//       child: Container(
//         // height: 50,
//         padding: const EdgeInsets.symmetric(
//           horizontal: 20,
//           vertical: 10,
//         ),
//         decoration: BoxDecoration(
//           color: const Color(0xFFA388EE),
//           borderRadius: BorderRadius.circular(30),
//           border: Border.all(
//             color: Colors.black,
//           ),
//           boxShadow: [
//             BoxShadow(
//               color: Theme.of(context).shadowColor,
//               spreadRadius: 1,
//               offset: const Offset(2, 3),
//             ),
//           ],
//         ),
//         child: Row(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Text(
//               text,
//               style: const TextStyle(
//                 color: Colors.black,
//                 fontWeight: FontWeight.w500,
//                 fontSize: 16,
//               ),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }
